<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Status_model extends CI_Model
{

    public $table = 'wp_status';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
      	$this->db->or_like('status', $q);
      	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
      	$this->db->or_like('status', $q);
      	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function buat_kode(){
          $this->db->select('RIGHT(wp_jabatan.id_jabatan, 2) as kode', FALSE);
          $this->db->order_by($this->id, $this->order);
          $this->db->limit(1);
          $query = $this->db->get($this->table, $this->id);      //cek dulu apakah ada sudah ada kode di tabel.
          if($query->num_rows() <> 0){
           //jika kode ternyata sudah ada.
           $data = $query->row();
           $kode = intval($data->kode) + 1;
          }
          else {
           //jika kode belum ada
           $kode = 1;
          }
          $kodemax = str_pad($kode, 2, "0", STR_PAD_LEFT); // angka 2 menunjukkan jumlah digit angka 0
          $kodejadi = "KR0".$kodemax;    // hasilnya ODJ-9921-0001 dst.
          return $kodejadi;
    }

    function cek_status($data)
    {
        $this->db->where('nama_status', $data);
        $cek = $this->db->get($this->table);
        if ($cek->num_rows() > 0) {
           return TRUE;
        } else return FALSE;
    }

    function cek_id_jabatan($id){
      $this->db->where('wp_jabatan_id', $id);
      $cek = $this->db->get('wp_karyawan');
      if ($cek->num_rows() > 0) {
          return TRUE;
      } else return FALSE;
    }
}

/* End of file Wp_jabatan_model.php */
/* Location: ./application/models/Wp_jabatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-09 07:12:23 */
/* http://harviacode.com */
