<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transaksi_model extends CI_Model
{

    public $table = 'wp_transaksi';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_transaksi', $q);
	$this->db->or_like('wp_barang_id', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('qty', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('tgl_transaksi', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->or_like('wp_pelanggan_id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('wp_status_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_transaksi', $q);
	$this->db->or_like('wp_barang_id', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('qty', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('tgl_transaksi', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->or_like('wp_pelanggan_id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('wp_status_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_data()
    {
        $this->db->select('wp_transaksi.id, wp_transaksi.id_transaksi, wp_transaksi.harga, wp_transaksi.qty, wp_transaksi.satuan, wp_transaksi.tgl_transaksi, wp_transaksi.updated_at, wp_transaksi.username, wp_barang.nama_barang, wp_pelanggan.nama_pelanggan, wp_status.status');
        $this->db->from($this->table);
        $this->db->join('wp_barang', 'wp_barang.id = wp_transaksi.wp_barang_id');
        $this->db->join('wp_pelanggan', 'wp_pelanggan.id = wp_transaksi.wp_pelanggan_id');
        $this->db->join('wp_status', 'wp_status.id = wp_transaksi.wp_status_id');
        $this->db->order_by($this->id_transaksi, $this->order);
        //$this->db->where('username');
        $data = $this->db->get();
        return $data->result();
    }

}

/* End of file Wp_transaksi_model.php */
/* Location: ./application/models/Wp_transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-12 05:09:32 */
/* http://harviacode.com */
