<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Suplier_model extends CI_Model
{

    public $table = 'wp_suplier';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function suplier_list(){
        $this->db->select("*");
        $this->db->from("wp_suplier");
        $hasil=$this->db->get();
        return $hasil->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_suplier', $q);
	$this->db->or_like('nama_suplier', $q);
	$this->db->or_like('alamat', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_suplier', $q);
	$this->db->or_like('nama_suplier', $q);
	$this->db->or_like('alamat', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->delete($this->table);
    }

    public function buat_kode()   {

          $this->db->select('RIGHT(wp_suplier.id_suplier, 2) as kode', 'LAST_INSERT_ID()', FALSE);
          $this->db->order_by($this->id, $this->order);
          $this->db->limit(1);
          $query = $this->db->get($this->table, $this->id);      //cek dulu apakah ada sudah ada kode di tabel.
          if($query->num_rows() <> 0){
           //jika kode ternyata sudah ada.
           $data = $query->row_array();
           $coba = $data['LAST_INSERT_ID()'];
           $kode = intval($data->kode) + $coba;
          }
          else {
           //jika kode belum ada
           $kode = $coba;
          }
          $kodemax = str_pad($kode, 2, "0", STR_PAD_LEFT); // angka 2 menunjukkan jumlah digit angka 0
          $kodejadi = "SP0".$kodemax;    // hasilnya ODJ-9921-0001 dst.
          return $kodejadi;
    }

}

/* End of file Wp_suplier_model.php */
/* Location: ./application/models/Wp_suplier_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-01 07:14:31 */
/* http://harviacode.com */
