<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_aset extends CI_Model
{

    public $table = 'wp_aset';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('wp_aset.id, wp_gudang.nama_gudang, wp_aset.aset_krat, wp_aset.aset_btl');
        $this->db->order_by('wp_aset.gudang', $this->order);
        $this->db->join('wp_gudang', 'wp_gudang.id = wp_aset.gudang', 'inner');
        $this->db->where('updated_by', $this->session->identity);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->where('updated_by', $this->session->identity);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
      	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
      	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->where('updated_by', $this->session->identity);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->where('updated_by', $this->session->identity);
        $this->db->delete($this->table);
    }

}

/* End of file Aset_model.php */
/* Location: ./application/models/Aset_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-12 04:37:16 */
/* http://harviacode.com */
